In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sys
sys.path.append('../')

In [2]:
%load_ext autoreload
%autoreload 2
from marcia import Likelihood
from marcia import Sampler

In [5]:
lh = Sampler('LCDM',['H0','Omega_m','r_d'],['CC','BAO-alam'])

In [6]:
lh.MLE([70,0.3,145])

Best-fit values: [ 68.14005401   0.31956571 147.24453223]
Max-Likelihood value (including prior likelihood):-7.454977465663671


array([ 68.14005401,   0.31956571, 147.24453223])

In [13]:
lh.logProb([70,0.3])

-8.771207326553315

In [17]:
lh.theory.hubble_rate([68,0.2,146],np.array([0.38, 0.51, 0.61]))

array([78.29904127, 82.97588594, 86.95425674])

In [24]:
lh.theory.hubble_rate([68,0.2,146],np.array([0.36, 0.51, 0.61]))

array([77.63057726, 82.97588594, 86.95425674])

In [25]:
lh.theory.transverse_distance([68,0.2,146],np.array([0.38, 0.51, 0.61]))

array([  0.        , 483.73081142, 836.75629887])